name: Frontend React CI

on:
  
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  
  workflow_dispatch:

defaults:
  
  run:
    working-directory: frontend

env:
  NODE_ENV: testing

jobs:
  build:
    
    name: Build code and run tests

    runs-on: ubuntu-latest
    
    steps:
      - name: Checking out commit ${{github.sha}}
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build --if-present
